### ISSUE TITLE
Read value live on sensor

### ISSUE THREAD

**Issue by paulolopes42** [yaq-project/hart-protocol#48]
I’m trying to develop a code to read information from a SEMTRONIX GD10 gas sensor, I used the example code, but got no response in print. I used the code below:
import hart_protocol
import serial

port = serial.Serial("COM9", 19200, timeout=0.1)
port.parity = "O"
port.stopbits = 1
address = 0xB3
port.write(hart_protocol.universal.read_unique_identifier(address))
#port.write(hart_protocol.universal.read_unique_identifier_associated_with_tag(address))
unpacker = hart_protocol.Unpacker(port)
for msg in unpacker:
    print(msg)

It does not show any error, but does not give any response message in print.

**Comment by untzag** [comment]
Are you sure that's your address, or is it your device ID? I'm not super familiar with short addresses in HART, I tend to use the full five byte address format.

https://github.com/yaq-project/hart-protocol/blob/main/hart_protocol/tools.py#L15

**Comment by paulolopes42** [comment]
Consegui fazer a leitura, obrigado
